### ISSUE TITLE
@applitools/eyes-selenium requires dom-utils@^4.7.4 (doesn't exist)

### ISSUE THREAD

**Issue by HananArgov** [applitools/eyes.sdk.javascript1#104]
looking at package.json, one of the dependencies is:
  `  "@applitools/dom-utils": "^4.7.4",`
when looking at the npm of `@applitools/eyes-selenium`, the latest version is 4.7.3

this issues an error:
```npm ERR! notarget No matching version found for @applitools/dom-utils@^4.7.4
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@applitools/eyes-selenium'

**Comment by tourdedave** [comment]
Looks like a botched deploy from earlier.

I've just published `@applitools/dom-utils@4.7.4` and confirmed it works when installing `@applitools/eyes-selenium@latest` from npm.
