### ISSUE TITLE
Tests Results output as junit for import to CI system

### ISSUE THREAD

**Issue by billhannah** [applitools/eyes.sdk.javascript1#124]
This issue was raised and closed as inactive in the old repo but was never addressed. The original issue is at https://github.com/applitools/eyes-storybook/issues/20

The original issue was as follows:

I want to import the results of the test run into my CI system (jenkins). To do this i would like the results results formatted as a junit file.

It looks like the rest results are stored in a structured way in https://github.com/applitools/Eyes.Sdk.JavaScript/blob/master/packages/eyes.sdk/src/TestResultsFormatter.js so this should be possible.

Even if you output the results in a structured json file i am happy to convert it to the junit format.

I am using storybook, but this issue may be better on the Eyes.Sdk.JavaScript repo, let me know if i should move it/link it

It was suggested to use the TAP file, but it is not granular enough for our CI purposes. If the results could be written to a JSON file, we could use that in our CI to record test passes and fails. You could emit the JSON objects that are output to the current log as `ServerConnector.matchSingleWindow - post succeeded TestResults of existing test {...}`

**Comment by tourdedave** [comment]
Hey @billhannah, thanks for the issue! I just want to understand your use case better.

Can you elaborate on why the TAP file wasn't granular enough? What kind of information were you looking for that wasn't there?

**Comment by billhannah** [comment]
In our case, we test against 4 browser profiles (Chrome, FF, IE11, and Chrome mobile size). So, if we had 5 stories, that would be 5 * 4, or 20 tests. But the TAP file lists only 5 tests (one for each story) rather than one for each screenshot.

Our CI system will report which story in which browser failed. We currently do this by outputting the log (with the `showLogs` option set to true) and parsing the output to find reports of failed stories. This is useful to gather metrics, such as `Story X has failed in IE 5 time in the last 10 runs (but fine in Chrome and Firefox)` to help spot storybook stories that need attention. But this approach is risky as any change to the log file format (which happened after the last update) breaks our CI.

Reporting at the Story + Browser level also helps when a person shipping a change can see immediately (without having to go to Eyes) that the area they changed ended up affecting areas they weren't expecting, allowing them to revert their change faster.

Finally, when multiple developers are shipping changes in the same build, the developer who is monitoring the build progress can see which Story + Browser failed so they can quickly alert the developer who caused the failure.

**Comment by tourdedave** [comment]
This has been released! It's available in version 3.7.0 of @applitools/eyes-storybook.

It's available through the `xmlFilePath` configuration option -- which takes a path to a directory. When specified, the test results will be written to a single eyes.xml file in that directory.

The configuration option is also documented under the Advanced Configuration section in the readme ([link](https://github.com/applitools/eyes.sdk.javascript1/blob/master/packages/eyes-storybook/README.md#advanced-configuration))
