### ISSUE TITLE
Cypress Run Issue - Cannot find module 'css-tree'

### ISSUE THREAD

**Issue by hunghau** [applitools/eyes.sdk.javascript1#141]
Oops...we found an error preparing this test file:

  /home/node/app/cypress/support/index.js

The error was:

Error: Cannot find module 'css-tree' from '/home/node/app/node_modules/@applitools/dom-snapshot/src/browser/cssom'

This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.

Here is the NPM log:
14 verbose pkgid efd-docker-cypress@0.0.1
15 verbose cwd /home/node/app
16 verbose Linux 4.19.76-linuxkit
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "cy:run"
18 verbose node v13.6.0
19 verbose npm  v6.13.6

This is with "@applitools/eyes-cypress": "^3.9.18"

I downgraded to "@applitools/eyes-cypress": "^3.9.17" and it works again.

**Comment by amitzur** [comment]
thanks for reporting, @hunghau !
version `3.9.18` indeed had an issue of a missing dependency which managed to pass undetected in our automation tests.
this is fixed in version `3.9.19`
