### ISSUE TITLE
This is the initial start page for the WebDriver server

### ISSUE THREAD

**Issue by speed-e** [applitools/eyes.sdk.javascript1#145]
I am running eyes-storybook v3.3.1 on my Storybook project, which works great for Firefox and Chrome. However, when we tried to add IE11 as a browser, it started throwing random errors saying: `This is the initial start page for the webdriver server`.

<img width="377" alt="Screenshot 2020-03-25 at 12 46 01" src="https://user-images.githubusercontent.com/13038383/77537816-a1fbb980-6e96-11ea-8ff5-4110925f172f.png">

This is only the case with IE11 as other browsers work fine, but I am mainly interested in running visual regression on IE. I thought it might be an issue due to too many browsers being used, so I have limited my config to:
```
module.exports = {
  showLogs: true,
  browser: [{ width: 1024, height: 768, name: 'ie11' }]
};
```

The error happens almost on every run, although it varies which component it fails on (we have 232 components in our component library). Ever so often, it will say that all tests have passed, but still fail with an error in the GitHub Action.

<img width="742" alt="Screenshot 2020-03-25 at 12 43 59" src="https://user-images.githubusercontent.com/13038383/77537699-66f98600-6e96-11ea-8357-1b80af051794.png">

Is there something that I am missing, could you please help? Our organisation is paying for a licence and we need IE11 support.

**Comment by amitzur** [comment]
Hi @speed-e ,

This is an old issue, so hopefully it is resolved by now.
For feature requests, feedback, and bug reports, please contact support@applitools.com
