### ISSUE TITLE
waitBeforeScreenshot on  per component params

### ISSUE THREAD

**Issue by BelloAdi** [applitools/eyes.sdk.javascript1#152]
Hey,
I saw on the docs that `waitBeforeScreenshot`  "is currently not available in the per component configuration." 
is it going to be supported soon?
because in some cases I need to wait for a specific element before the screenshot and I don't want to increase the global `waitBeforeScreenshot` in my config for all tests :\

Meanwhile, is there any better solution to hold specific story? instead of increasing the waiting time on my config for all stories?
thanks :)

**Comment by FinestV** [comment]
The docs read "Note that the predicate option for waitBeforeScreenshot is currently not available in the per component configuration."

Sounds like you are wanting to use a wait time? That should be fine as it isn't the predicate option.

**Comment by amitzur** [comment]
Hi @BelloAdi,
Sorry for the late response, somehow this got lost. @FinestV answered correctly, but there's also the `runBefore` function for performing interactions with stories, and it can also serve for waiting on a condition, as the snapshot is taken after the function resolves.

Here's the relevant section in the docs: https://www.npmjs.com/package/@applitools/eyes-storybook#runbefore

**Comment by BelloAdi** [comment]
Thanks @amitzur, will give it a try.
