### ISSUE TITLE
@applitools/sdk-fake-eyes-server was removed from NPM

### ISSUE THREAD

**Issue by igolopolosov** [applitools/eyes.sdk.javascript1#156]
Hello, recently we found that `@applitools/sdk-fake-eyes-server` was removed from NPM and our pipelines started to fail.
![image](https://user-images.githubusercontent.com/8162439/79206258-fc08f280-7e36-11ea-9f03-918a2ce209ab.png)

Do you you know why it could have happened?

https://www.npmjs.com/search?q=applitools%2Fsdk-fake-eyes-server

**Comment by igolopolosov** [comment]
@amitzur Hello :) maybe you could shed the light?

**Comment by amitzur** [comment]
@igolopolosov there shouldn't be any public package of ours that's dependent on `@applitools/sdk-fake-eyes-server`. What SDK and version are you using?

**Comment by amitzur** [comment]
@igolopolosov in the meantime I made it public again so you shouldn't get these errors.

**Comment by igolopolosov** [comment]
Thank you @amitzur it was `@applitools/eyes.webdriverio v2.11.8` using it :)

We updated `@applitools/eyes.webdriverio`  from `2.11.8` to `2.12.8` and it's not a problem anymore, however I suspect that some private projects like ours might still use it.

**Comment by amitzur** [comment]
We'll keep this dependency public, so that no projects anywhere would break.
Thanks for letting us know, @igolopolosov !

**Comment by SriGitHubSri** [comment]
> We'll keep this dependency public, so that no projects anywhere would break.
> Thanks for letting us know, @igolopolosov !

Hi,

We tried to install @appitools/eyes-webdriverio@5.9.4 and got the same issue that 
**@applitools/sdk-fake-eyes-server@^1.0.3 is not in the npm registry**

Please could you help with removing this dependency?

**Comment by tourdedave** [comment]
> > We'll keep this dependency public, so that no projects anywhere would break.
> > Thanks for letting us know, @igolopolosov !
> 
> Hi,
> 
> We tried to install @appitools/eyes-webdriverio@5.9.4 and got the same issue that
> **@applitools/sdk-fake-eyes-server@^1.0.3 is not in the npm registry**
> 
> Please could you help with removing this dependency?

Handled in #265.
