### ISSUE TITLE
setForceFullPageScreenshot doesn't work after version 5.8.4

### ISSUE THREAD

**Issue by marcoaam** [applitools/eyes.sdk.javascript1#168]
I am trying to upgrade applitools/eyes-webdriverio to a greater version than 5.8.4 but after many different attempts to get setForceFullPageScreenshot to work it seems like it is broken after this version. It doesn't take the screenshot of the full page when enabled. 

It correctly identifies the height of the page. But it doesn't capture all the content within it. It just captures the background colour on the parts that are outside of the viewport.

**Comment by tourdedave** [comment]
@marcoaam is this resolved now?

**Comment by marcoaam** [comment]
sort of @tourdedave. We contacted support and was provided with a workaround which worked

![image](https://user-images.githubusercontent.com/7504870/84023130-72c9f400-a97f-11ea-9b74-46851f7c7f12.png)

However, we are getting a separate issue with some of the browsers which another member of the team is trying to discuss with support. 

Happy to reopen if the fix provided is just a workaround and not the normal behaviour.

**Comment by tourdedave** [comment]
This is normal. It is a common workaround that's needed when the application being tested has changed the default scroll behavior. You need to retarget the SDK to the root element which will scroll. That, or use JavaScript to unset to the styles which alter the scroll behavior. The former is more reasonable than the latter (although both are sufficient).
