### ISSUE TITLE
Cannot read property 'sessionID' of undefined error when using webdriverIO v5

### ISSUE THREAD

**Issue by meenakshisatpathy** [applitools/eyes.sdk.javascript1#192]
Error message: Cannot read property 'sessionID' of undefined

Environment:
WebdriverIO V5.18.6
@applitools/eyes.webdriverio - 2.17.0,

Code snippet:

```
describe('Applitools tests', async () => {
    it('Page should look ok', async () => {
        await browser.url('https://applitools.com/helloworld')
        try {
            const viewPortSize = await browser.getWindowSize();
            console.log('check', viewPortSize)
            await eyes.open(browser, 'Hello world example', 'test1', viewPortSize)
            await eyes.check('Main page', Target.window())
            await (await $('<button />')).click
            await eyes.check('After click', Target.window())
        } finally{
            await eyes.abortIfNotClosed();
        }
    });
})
```

Already referred doc:
https://applitools.com/docs/api/eyes-sdk/classes-gen/class_eyes/method-eyes-open-webdriverio_sdk5-javascript.html#

Note:
I have run the code with out using Applitool, and it gets executed successfully.
Also, able to read session id using
`browser.sessionId`

**Comment by amitzur** [comment]
Hi @meenakshisatpathy, `@applitools/eyes.webdriverio` is our package for webdriver.io **version 4**.
For version 5 and above, please use `@applitools/eyes-webdriverio` (with a dash instead of dot).

We realize this is bad naming. We intend to add Readme's to make this more explicit.
