### ISSUE TITLE
Update Eyes Service Class to handle FileLogger + WebdriverIO

### ISSUE THREAD

**Issue by AutomationReddy** [applitools/eyes.sdk.javascript1#222]
I see Eyes Service Class in eyes/webdriverio - 5.18.X has no capability to save the logs to an external file using FileLogger class. It only has Console Logger. 

**See below:**

```
beforeSession(config, _capabilities, _specs) {
    this._eyes.setConfiguration(this._eyesConfig)
    this._appName = this._eyes.getConfiguration().getAppName()
    if (config.enableEyesLogs) {
      this._eyes.setLogHandler(new ConsoleLogHandler(true)) // I have no option to go with FileLogger
    }
  }
```
Ask for an extra input in WDIO config like logType = 'FILELOGGER' (Default: CONSOLELOGGER) and this is optional and works only if enableEyesLogs = true

**New Implementation is something like:**

```
beforeSession(config, _capabilities, _specs) {
    this._eyes.setConfiguration(this._eyesConfig)
    this._appName = this._eyes.getConfiguration().getAppName()
    if (config.enableEyesLogs) {
      config.logType.toLowercase() === 'filelogger' ? this._eyes.setLogHandler(new FileLogHandler(true)) : 
                                                                                   this._eyes.setLogHandler(new ConsoleLogHandler(true))
    }
  }
```
**This is for the users who uses EyesService class and I cannot access eyes as it is not global to provide some runtime settings.**

**Comment by amitzur** [comment]
Hi @AutomationReddy ,

This is an old issue, so hopefully it is resolved by now.
For feature requests, feedback, and bug reports, please contact support@applitools.com
