### ISSUE TITLE
Unable to install, `monitoring-commons` not found, 404

### ISSUE THREAD

**Issue by IanVS** [applitools/eyes.sdk.javascript1#229]
I am using `"@applitools/eyes-storybook": "3.2.5"` and recently I have started to get the following error when I try to install it:

```
error An unexpected error occurred: "https://registry.yarnpkg.com/@applitools/monitoring-commons/-/monitoring-commons-1.0.19.tgz: Request failed \"404 Not Found\"".
```

Was this somehow removed from the registry?  I see at least two other closed issues pointing to missing npm files, so maybe there's a problem with how you are managing dependencies?  Why does this happen?

**Comment by IanVS** [comment]
I tried upgrading to `3.8.5`, and am getting:

```
error Couldn't find package "@applitools/feature-flags@2.1.1" required by "@applitools/visual-grid-client@14.6.0" on the "npm" registry.
```

**Comment by amitzur** [comment]
@IanVS Checking this now. It will be resolved shortly.

**Comment by IanVS** [comment]
Thanks for the quick response, @amitzur! 👏

**Comment by amitzur** [comment]
@IanVS issue resolved.

**Comment by IanVS** [comment]
I am indeed able to install now.  Thanks again.
