### ISSUE TITLE
My Applitools tests are flaky

### ISSUE THREAD

**Issue by jack-todd** [applitools/eyes.sdk.javascript1#246]
My Applitools tests are so incredibly flaky and unreliable.
Can you please fix this or should I just use the free imagemagick library instead/

**Comment by tourdedave** [comment]
Hey @jack-todd, sorry to hear that. But this is the issue tracker for the Applitools SDKs, not the Applitools service itself. If you're having stability issues in your tests then you can contact support@applitools.com to see if they can help. You will need to provide specifics about your problem (e.g., a reproducible example of the issue you're experiencing).
