### ISSUE TITLE
eyes-storybook(feature request): show only non-passing tests in the output report

### ISSUE THREAD

**Issue by shlomitc** [applitools/eyes.sdk.javascript1#256]
As we've reached the point of 1k+ tests, some machines cannot handle the output log properly, cutting the report's output.
This means that we can't see the bottom line including the link to the applitools dashboard.

I would like to suggest showing an output that includes only the **non-passing tests**, which means it will extremely reduce the log and also focus only on what requires my attention.

This could also be configurable in case you don't think this should be the default behavior.

thanks

**Comment by amitzur** [comment]
@shlomitc makes sense. We'll discuss your feedback and update. Thanks!

**Comment by EgoziE** [comment]
@amitzur Thanks!
We currently have 1020 tests (and counting..)
Please add a way to reduce logs, they just cut in the middle:
![image](https://user-images.githubusercontent.com/35173937/92574472-cd7d2f80-f28f-11ea-9cef-675e5e684afc.png)

**Comment by EgoziE** [comment]
Hey @amitzur 
Can you please address this issue?
I can try to create a PR if you want to help me with some instructions...

**Comment by amitzur** [comment]
This is an old issue, so hopefully it is resolved by now.
For feature requests, feedback, and bug reports, please contact support@applitools.com
