### ISSUE TITLE
Error: @applitools/sdk-fake-eyes-server@^1.0.3 is not in the npm registry for eyes-webdriverio@5.9.4

### ISSUE THREAD

**Issue by SriGitHubSri** [applitools/eyes.sdk.javascript1#265]
Hi,

We tried to install @applitools/eyes-webdriverio@5.9.4 and got the same issue that
@applitools/sdk-fake-eyes-server@^1.0.3 is not in the npm registry

Please could you help with removing this dependency?

**Comment by tourdedave** [comment]
Removing the dependency and shipping another version is problematic, but I just made the package public. Try installing again.

**Comment by SriGitHubSri** [comment]
> Removing the dependency and shipping another version is problematic, but I just made the package public. Try installing again.

Thanks very much for your quick help here . I tried **npm i @applitools/eyes-webdriverio@5.9.4** once again and it works fine now
