### ISSUE TITLE
No TypeScript type definitions

### ISSUE THREAD

**Issue by Phonesis** [applitools/eyes.sdk.javascript1#266]
I have just installed latest @applitools/eyes-protractor 

Am using TypeScript with Protractor and cannot get the types. Is there no @Types definition file or npm package available?

**Comment by Phonesis** [comment]
any update on this?

**Comment by amitzur** [comment]
@Phonesis we're working to get the best quality type definitions for the SDK.
We are nearing completion, and will update next week on estimated time for release.

**Comment by declancarrollcb** [comment]
I am also interested in this. It would be great to have types. Do you know which of the packages would be supported? I am currently using: @applitools/eyes-images.

**Comment by kyryloonufriiev** [comment]
We have TS support for the protractor since version `1.16`
@declancarrollcb answering your question - unfortunately, `@applitools/eyes-images` doesn't have TS support yet. It has to be prioritized.
