### ISSUE TITLE
The new version (3.9.2) is broken and can't be installed

### ISSUE THREAD

**Issue by sivanharel** [applitools/eyes.sdk.javascript1#278]
When trying to install the new version 3.9.2 I am getting the following error:

npm ERR! notarget No matching version found for @applitools/dom-snapshot@4.2.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@applitools/eyes-storybook'
npm ERR! notarget

**Comment by sivanharel** [comment]
Sorry it was an issue on our side.

**Comment by amitzur** [comment]
@sivanharel glad to hear it's resolved
