### ISSUE TITLE
Unable to set a viewport

### ISSUE THREAD

**Issue by nagornyi** [applitools/eyes.sdk.javascript1#282]
I'm unable to set a viewport in Applitools Eyes after upgrading to the latest 4.46.1 npm version, it's always fixed to 800x600 now. This code doesn't work anymore, but it used to work in the previous Eyes version.

```
await eyes.open(
driver,
"My App Name",
"My Scenario Name",
{ width: 412, height: 869 }
);
```

These are my package versions:
```
"@applitools/eyes-selenium": "4.46.1",
"selenium-webdriver": "4.0.0-alpha.7",
"chromedriver": "86.0.0",
```

**Comment by amitzur** [comment]
@nagornyi We would need the SDK's logs and platform information find out the reason for this issue.
Please shoot an email to support@applitools.com with these details and we will look at it.
Thanks!

**Comment by nagornyi** [comment]
It always defaults to 800x600, no matter what viewport size I try to set (I even tried 1024x768), and there are no exceptions in the log other than what you can see below. The platform is Ubuntu 20.04 LTS, Chrome Version 86.0.4240.198 (Official Build) (64-bit), NodeJS v12.18.3. I also tried to use the static setViewportSize method with the same results. Setting viewport to the same size worked in the previous versions of Applitools, but it doesn't work in the latest version.

2020-11-12T10:17:41Z Eyes: [VERBOSE] {} Object.getViewportSize(): EyesUtils.getViewportSize()
2020-11-12T10:17:41Z Eyes: [VERBOSE] {} Object.getViewportSize(): Done! Viewport size:  {"height":600,"width":800}
2020-11-12T10:17:41Z Eyes: [VERBOSE] {} Object.startSession(): Application environment is [OS = ? HostingApp = ? DisplaySize = 800x600]
2020-11-12T10:17:41Z Eyes: [VERBOSE] {} Object.startSession(): Starting server session...

**Comment by nagornyi** [comment]
Ok, I found the easy way to reproduce the issue. Somehow the **user agent** prevents the viewport size setting and then it defaults to 800x600, but it happens only in **headless** Chrome mode. So if you want to reproduce it, just make sure that you have these two additional Chrome options:
```
chromeOptions.addArguments("--headless");
chromeOptions.addArguments("--user-agent=Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Mobile Safari/537.36");
```

**Comment by kyryloonufriiev** [comment]
@nagornyi the ua you demonstrate in the previous comment contains `Mobile`, so we treat this ua as ua of the mobile device. It doesn't make sense to change viewport size on mobile devices. If you want to use this custom ua string then maybe it makes sense to use chrome emulation options with preset viewport size.

**Comment by amitzur** [comment]
Hi @nagornyi ,

This is an old issue, so hopefully it is resolved by now.
For feature requests, feedback, and bug reports, please contact support@applitools.com
