### ISSUE TITLE
process.hrtime is not a function

### ISSUE THREAD

**Issue by talaikis** [applitools/eyes.sdk.javascript1#292]
adding this package to the latest cypress gives the above error

**Comment by amitzur** [comment]
Hey @talaikis , thanks for reporting!
Please add more details, as we cannot work on this item with this information only.
The best way to pass this information is by sending an email to `support@applitools.com`

**Comment by jfalleur** [comment]
I was just able to reproduce this same issue for a customer. In their case the support/index.js file contained the following line within their module.exports:

`require('@applitools/eyes-cypress')(module);`

Removing this resolved the issue.

**Comment by amitzur** [comment]
Thanks @jfalleur . This indeed happens when the line that needs to be added to the pluginsFile is accidentally added to the supportFile.
