### ISSUE TITLE
Add Set scroll root element option/method

### ISSUE THREAD

**Issue by sivapriya-k** [applitools/eyes.sdk.javascript1#319]
Hello,

Eyes selenium has a method to override/set scroll root element. Is it possible to add a method/option for eyes cypress sdk too? Right now, check window with target/selector is not working if the scroll is not set on the body but in a different element. It only captures what is visible on the viewport

Thanks!

**Comment by tourdedave** [comment]
eyes-cypress only supports running on the visual grid, where using a scroll root element is not going to be helpful. The best way to handle this kind of issue is with a before capture screenshot hook. With it you can specify a JavaScript snippet as a string that you would like to run on the page before the visual grid captures a screenshot. It's useful for adjusting attributes on the page to fix scrolling issues (e.g., so it can be restored back to the body of the page). You can see more details about it [here in the readme](https://github.com/applitools/eyes.sdk.javascript1/blob/master/packages/eyes-cypress/README.md#beforecapturescreenshot-a-script-that-runs-after-the-page-is-loaded-but-before-taking-the-screenshot-for-example). If you need more help or run into any other issues, you can email support@applitools.com for assistance.
