### ISSUE TITLE
Using custom eyes configuration per component with "Component Story Format"

### ISSUE THREAD

**Issue by liorcode** [applitools/eyes.sdk.javascript1#331]
In the docs, all the custom configuration uses a 3rd argument of the`storiesOf` function:
https://github.com/applitools/eyes.sdk.javascript1/tree/master/packages/eyes-storybook#waitbeforescreenshot
However, I use the new "[Component Story Format](https://storybook.js.org/docs/react/api/csf)"
How can I pass custom configuration, such as "waitbeforescreenshot" parameter (per component)?

**Comment by amitzur** [comment]
Here's an example of how to use the Applitools Storybook SDK with CSF format: https://github.com/applitools/storybook-csf-example

**Comment by liorcode** [comment]
thanks @amitzur! worth adding it to the `eyes-storybook` docs i believe 👍
