### ISSUE TITLE
eyes-cypress: '@applitools/snaptdout@1.0.1' is not in the npm registry

### ISSUE THREAD

**Issue by michaelbrewer** [applitools/eyes.sdk.javascript1#397]
Was `@applitools/snaptdout@1.0.1` removed?  Because installing `@applitools/eyes-cypress` now fails which is breaking our CI pipeline

```shell
$ npm i -D @applitools/eyes-cypress
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@applitools%2fsnaptdout - Not found
npm ERR! 404
npm ERR! 404  '@applitools/snaptdout@1.0.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '@applitools/eyes-cypress'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

```

**Comment by tool3** [comment]
@michaelbrewer looks like a glitch in npm.

I remember setting this package to `public` specifically. when I went to see it in npm it said `private`.

I then looked in the package settings, and from that moment on, it remained public, so you should be able to retry what you were doing.

**Comment by michaelbrewer** [comment]
Thanks @tool3  working again
