### ISSUE TITLE
eyes-cypress - Port is undefined

### ISSUE THREAD

**Issue by LeJeanbono** [applitools/eyes.sdk.javascript1#402]
![image](https://user-images.githubusercontent.com/11347342/111055104-d2a37d00-8472-11eb-85bb-f1b8a6cc5546.png)
My test : 
```js
cy.eyesOpen({
    appName: 'Hello World!',
    testName: 'My first JavaScript test!',
    browser: {width: 800, height: 600},
});
cy.eyesCheckWindow({
    tag: 'Login screen', target: 'region', selector: {
        type: 'css',
        selector: '#genres'
    }
});
cy.eyesClose();
```

**Comment by jspkiel** [comment]
Similar situation here

![Screenshot 2021-04-04 at 04 05 42](https://user-images.githubusercontent.com/12475983/113497350-331a5d00-94fb-11eb-8179-7236a721938c.png)

**Comment by tool3** [comment]
@LeJeanbono @jspkiel we start a node server on port `0` to get a free port from the running machine. it appears that in both cases - this didn't happen for some reason.

can you please share your operating system ?

also, please run this nodejs snippet:
```javascript
const https = require('https');
const server = https.createServer();
server.listen(0, e => {
  if (e) throw e;
  console.log(server.address().port);
  server.close();
});
```
you can also run it as a one-liner if that's more convenient:
```bash
node -e "const https = require('https');const server = https.createServer();server.listen(0, e => { if (e) throw e; console.log(server.address().port); server.close();});"
```

it should print a port number and exit, unless an error is encountered.
please share the output of this snippet as well.

thanks !

**Comment by jspkiel** [comment]
Thanks for your reply @tool3 

My OS is `macOS Mojave Version 10.14.6`

I run the script and it does indeed get a random port back 

![image](https://user-images.githubusercontent.com/12475983/114014207-43666b00-9860-11eb-91ed-ff4a29f9493c.png)

Is there anything else I could run to give you more information as to why this issue occurs?

thanks!

**Comment by LeJeanbono** [comment]
I obtain a random port (58908)
---
Windows
Node 14.9.0

**Comment by Ed-Jamal** [comment]
hi @tool3, any update on this?

**Comment by tool3** [comment]
hey all, please send an email to support@applitools.com so we can have more focus around this issue. thanks !
