### ISSUE TITLE
Blank iframes for Safari browser

### ISSUE THREAD

**Issue by groov1kk** [applitools/eyes.sdk.javascript1#406]
While taking screenshots using the cypress there are blank iframes in Safari browser.

Target was window for the both cases. 

Versions:
cypress 6.3.0, 6.6.0
eyes-cypress: 3.20.4

**Comment by amitzur** [comment]
Hi @groov1kk ,

This is an old issue, so hopefully it is resolved by now.
For feature requests, feedback, and bug reports, please contact support@applitools.com
