### ISSUE TITLE
Exception in thread "main" javax.ws.rs.ProcessingException: java.net.UnknownHostException: eyesapi.applitools.com: nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by stephenws** [applitools/eyes.sdk.javascript1#42]
I am running this sample code Java-Selenium

package Invison;

import java.net.URISyntaxException;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import com.applitools.eyes.selenium.Eyes;

public class Invisioneye {

	public static void main(String[] args) throws URISyntaxException, InterruptedException {

		WebDriver driver = new ChromeDriver();

// Use your own api key, make sure you use it in all your tests.
		Eyes eyes = new Eyes();
		eyes.setApiKey("My Key");

		try {
// Start visual testing with browser viewport set to 1024x768.
// Make sure to use the returned driver from this point on.
			driver = eyes.open(driver, "Applitools", "Test Web Page");

			driver.get("http://applitools.com");

// Visual validation point #1
			eyes.checkWindow("Main Page");

			driver.findElement(By.cssSelector(".features>a")).click();

// Visual validation point #2
			eyes.checkWindow("Features Page");

// End visual testing. Validate visual correctness.
			eyes.close();

		} finally {
// Abort test in case of an unexpected error.
			eyes.abortIfNotClosed();
			driver.quit();
		}
	}
}

It gives me Error

**Comment by astappiev** [comment]
Looks like you have a proxy issue. Check your system proxy.
Also you need to set correct API_KEY before sending request.

Thanks for reporting.

P.S. this is a repository of JavaScript client, you can create a new issue in [Java client](https://github.com/applitools/eyes.sdk.java3) repository.
