### ISSUE TITLE
`@applitools/eyes-webdriverio` package currently not usable with WebdriverIO v7

### ISSUE THREAD

**Issue by christian-bromann** [applitools/eyes.sdk.javascript1#420]
Hey y'all,

it seems that currently the SDK doesn't support WebdriverIO v7 which was released back in February. Would it be possible to update the peerdep range of `@applitools/eyes-webdriverio` to allow usage of v7 as well? There shouldn't be any breaking changes given that the codebase doesn't TypeScript.

I remember talking with @amitzur about potentially deprecating the `@wdio/applitools-service` in favor of an `@applitools/eyes-webdriverio-service`. I believe it would be much more efficient if the Applitools team could maintain their own integration.

Is the team still interested going that route?

**Comment by kyryloonufriiev** [comment]
@christian-bromann Hey,

We have updated `@applitools/eyes-webdriverio` to version `5.31` and include v7 in peerdeps range.

Regarding `@applitools/eyes-webdriverio-service` we are maintaining this package and keep it updated, would you like to deprecate `@wdio/applitools-service`? I also have a question about cli integration do we have to rename our package to `wdio-applitools-service` in order to make it 100% integrated?

**Comment by christian-bromann** [comment]
> would you like to deprecate `@wdio/applitools-service`?

Sure, see webdriverio/webdriverio#6884

> I also have a question about cli integration do we have to rename our package to `wdio-applitools-service` in order to make it 100% integrated?

Packages following the name scheme can be applied via string in the wdio config, e.g.

```js
services: ["applitools"]
```
it is always possible to add any arbitrary package to the list, by importing it, e.g.:
```js
import ApplitoolsService from '@applitools/eyes-webdriverio'
export const config = {
  // ...
  services: [[ApplitoolsService, {}]]
  // ...
}
```

I still "own" the `wdio-applitools-service` package but happy to share access rights.

**Comment by christian-bromann** [comment]
I deprecated `@wdio/applitools-service` and will remove the package from the WebdriverIO repo in https://github.com/webdriverio/webdriverio/pull/6884. Thanks so much for maintaining the package.
