### ISSUE TITLE
png-async dependency causes installation issues

### ISSUE THREAD

**Issue by klamping** [applitools/eyes.sdk.javascript1#43]
`eyes.sdk.core` includes a dependency for the package 'png-async', which unfortunately [has a show-stopping bug](https://github.com/kanreisa/node-png-async/issues/3).

Unfortunately, png-async hasn't been updated in two years, which means that issue is likely to go unaddressed for a while. It looks like it will need to be replaced with a more up-to-date package. 

Looking at png-async, the last version without the file is 0.9.0. There's no changelog for the project, but from what I can tell from [the commit history](https://github.com/kanreisa/node-png-async/commits/master), the only differences are a few cosmetic upgrades.

I believe downgrading to 0.9.0 shouldn't impact usage and can be done safely, although I'm not sure exactly what would need to be regression tested.

**Comment by astappiev** [comment]
`png-async` package updated to v. 0.9.3, where the issue is solved.

**Comment by klamping** [comment]
Confirmed this is now fixed! Wahoo!
