### ISSUE TITLE
element.getSize is not a function

### ISSUE THREAD

**Issue by itajaja** [applitools/eyes.sdk.javascript1#52]
`getSize` is not a function in [vanilla selenium](https://seleniumhq.github.io/selenium/docs/api/javascript/index.html) ([changelog](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/CHANGES.md#changes-for-w3c-webdriver-spec-compliance)), so it's impossible to call checkElement or checkRegion with the latest selenium. I see that `getSize` is used multiple times throughout the codebase, is this going to be fixed soon? It is currently impossible to use anything other than `checkWindow`.

**Comment by itajaja** [comment]
oops, wrong repo, moved to the selenium specific repo https://github.com/applitools/Eyes.Selenium.JavaScript/issues/67

**Comment by itajaja** [comment]
cool. any ETA? Thanks!

**Comment by astappiev** [comment]
Should be last Friday :)
I can guarantee only this week (it may be tomorrow as well). I just need to
finish some more priority tasks before.

**Comment by astappiev** [comment]
Hi @itajaja !

We released a new version based on Selenium 4 (alpha1). Please, check out this package https://www.npmjs.com/package/@applitools/eyes-selenium

Unfortunately, there are no docs for this version on our website, you can check examples in [this folder](https://github.com/applitools/eyes.sdk.javascript1/tree/v4.0.0/eyes-selenium/example), also more examples [inside tests](https://github.com/applitools/eyes.sdk.javascript1/tree/v4.0.0/eyes-selenium/test/integration).

But take into account that Selenium client for nodejs is still in alpha version and contains a lot of issues. Few of them we fixed inside our SDK, but not all functions working now, e.g. it is unpossible to use Appium WebDrrive.

Also, we greatly updated our SDK in comparison to the previous version [eyes.selenium (0.0.83)](https://www.npmjs.com/package/eyes.selenium) and it, also, possible contain few issies as it is a fresh version.

Best regards,
Oleh

**Comment by itajaja** [comment]
perfect, I'll be happy to flag some issues as I encounter them. thanks!
