### ISSUE TITLE
Cypress test runs for very long time

### ISSUE THREAD

**Issue by seb-thomas** [applitools/eyes.sdk.javascript1#592]
I originally thought the test wasn't finished and spent ages trying to debug that, but it turns out the test does finish but some times after a minute after the testing is done

eyesClose is called after about 1 second, but the test keeps running and batchEnd is called many times

My set up is as per this repo's readme

![image](https://user-images.githubusercontent.com/629571/118101137-2aa52400-b3cf-11eb-8fa0-3cdea7ea7c30.png)

**Comment by tool3** [comment]
@seb-thomas please send an email to support@applitools.com for further investigation into this issue. thanks !
