### ISSUE TITLE
Slow execution time when using eyes-testcafe sdk

### ISSUE THREAD

**Issue by NHP95** [applitools/eyes.sdk.javascript1#636]
I have a test suite of 64 BDD scenarios and it took ~7 minutes to execute them all. As I converted 26 of them to adapt eyes-testcafe sdk (e.g. call checkWindow at the end of each scenario), the execution went from 7 mins to 20 mins. As I'm aware, my account has UFG enabled, is it an expected value of execution time? FYI, there's just Chrome specified in **browser** property of my config file.

**Comment by amitzur** [comment]
Hi @NHP95 ,

This is an old issue, so hopefully it is resolved by now.
For feature requests, feedback, and bug reports, please contact support@applitools.com
