### ISSUE TITLE
eyes-storybook not compatible with Storybook 6.3

### ISSUE THREAD

**Issue by dayton-bobbitt** [applitools/eyes.sdk.javascript1#655]
### The issue
Running `npx eyes-storybook` will throw the following error when Storybook `^6.3.0` is installed:
> Error when reading stories: could not determine storybook version in order to extract stories

From what I can tell, it seems that one of the CSS selectors used by eyes-storybook to determine which version of Storybook is running is no longer matching the expected elements.

I've temporarily pinned our Storybook version to `~6.2.0` to prevent the error from occurring. 

### Our environment
* node 14
* Storybook 6.3.0 ([released 6/23/2021](https://github.com/storybookjs/storybook/releases/tag/v6.3.0))
* @applitools/eyes-storybook 3.22.3

**Comment by tool3** [comment]
hey @dayton-bobbitt, I wasn't able to reproduce this with said versions. it works for me.

can you please run with `showLogs: true` in `applitools.config.js` (or through the cli flag) and attach the console output ?
