### ISSUE TITLE
Cypress: eyesCheckWindow of region ignores fully argument

### ISSUE THREAD

**Issue by robaw** [applitools/eyes.sdk.javascript1#664]
### Issue
When using the selector to identify the scrollable target to screenshot and supplying the argument 'fully:true', Applitools ignores this and only takes the screenshot of the viewport. This is supposed to be [supported in Javascript](https://help.applitools.com/hc/en-us/articles/360037441472-Determining-the-Scrollable-Element-to-get-a-Full-Page-Screenshot) but doesn't seem to work with Cypress SDK.

### Example
[Example Page](https://www.skyscanner.net/transport/flights/edi/bcn/210729/?adultsv2=1&cabinclass=economy&childrenv2=&inboundaltsenabled=false&is_banana_refferal=true&outboundaltsenabled=false&preferdirects=false&ref=home&rtn=0#/details/11235-2107290725--32174,-31685-1-9772-2107291535/index/2)

Example check:
```
    cy.eyesCheckWindow({
      tag: 'booking panel',
      target: 'region',
      selector: '*[id=details-modal]',
      fully: true,
    });
```

**Comment by amitzur** [comment]
Hi @robaw ,

This is an old issue, so hopefully it is resolved by now.
For feature requests, feedback, and bug reports, please contact support@applitools.com
