### ISSUE TITLE
Update Puppeteer (and other) tutorials

### ISSUE THREAD

**Issue by vdhpieter** [applitools/eyes.sdk.javascript1#665]
The code in [the current puppeteer tutorial](https://applitools.com/tutorials/puppeteer.html) is outdated. Specifically the beginning:
```ts
// Create a runner with concurrency of 1
const runnerOptions = new RunnerOptions().testConcurrency(1)
runner = new VisualGridRunner(runnerOptions);
```
The `new` keyword just gives me an error and using the RunnerOptions I get 2 deprecation warnings:
```
The signature '(): RunnerOptionsFluent' of 'RunnerOptions' is deprecated.ts(6387)
index.d.ts(1997, 5): The declaration was marked as deprecated here.

The signature '(options?: RunnerOptionsFluent | undefined): VisualGridRunner' of 'VisualGridRunner' is deprecated.ts(6387)
index.d.ts(1555, 7): The declaration was marked as deprecated here.
```

But I can't find anywhere in the repo what the correct way to do this is...

**Comment by amitzur** [comment]
@vdhpieter the correct way to do it is
```
const runner = new VisualGridRunner({testConcurrency: 1})
```
We will work to improve the tutorial. Thanks for raising this issue.
