### ISSUE TITLE
[eyes-storybook] Update Puppeteer Package Dependency

### ISSUE THREAD

**Issue by dvandyke** [applitools/eyes.sdk.javascript1#666]
**Is your feature request related to a problem? Please describe.**

The `eyes-storybook` package currently references [puppeteer@1.20.0](https://github.com/applitools/eyes.sdk.javascript1/blob/62e6b234d1d9ac7494bab4dc8823b71954b8f5a0/packages/eyes-storybook/package.json#L72) which corresponds to a Chromium version of 78.0.3882.0. 
This is pretty out of date and results in tests running in an environment missing many browser/DOM APIs (e.g.`replaceChildren`)

I haven't found a workaround or other way to load a different version of puppeteer/chromium when running `eyes-storybook`

![image](https://user-images.githubusercontent.com/7915755/127727725-74c115af-df8c-47b5-a9ac-eeee95abccd4.png)

**Describe the solution you'd like**
Can we bump to a more recent/latest version of puppeteer? Within the past year?

**Comment by amitzur** [comment]
@dvandyke we are working to upgrade the puppeteer version. In the meantime a workaround is to specify Chrome's `executablePath`, as described here: https://www.npmjs.com/package/@applitools/eyes-storybook#running-eyes-storybook-in-docker

**Comment by amitzur** [comment]
Hi @dvandyke ,

We have upgraded Puppeteer version.
For feature requests, feedback, and bug reports, please contact support@applitools.com
