### ISSUE TITLE
eyes-storybook@3.22.7 - all stories fail with "Cannot read property 'evaluateHandle' of undefined"

### ISSUE THREAD

**Issue by liorcode** [applitools/eyes.sdk.javascript1#669]
After upgrading to eyes-storybook to the latest version (3.22.7), all the stories now fail with the following error:
`Story - Failed [page 1] Failed to get story data for "Story". TypeError: Cannot read property 'evaluateHandle' of undefined`
For now, I've pinned the version at 3.22.6

**Comment by amitzur** [comment]
@liorcode this was fixed in version `3.22.8` which was released a couple of hours after `3.22.7`.
