### ISSUE TITLE
Use match layout fails with IllegalType error

### ISSUE THREAD

**Issue by silvanaweb** [applitools/eyes.sdk.javascript1#691]
Hi, I tried to use layout as described in the docs, but I keep getting this error:

```
Errors - 1 tests
         ✖ [Eyes test not started] : Error: IllegalType: left is not a number
```

This is the way I am setting the "eyesCheckWindow" props:
```

{
        tag: `${viewportName}.devicePage.iphone.initial`,
        target: "region",
        layout: [
          { top: 100, left: 0, width: 1000, height: 100 },
          { selector: context },
        ]
      }
```

I tried with and without this line: { top: 100, left: 0, width: 1000, height: 100 }.

Of course the test works without layout.

**Comment by amitzur** [comment]
Hi @silvanaweb ,

This is an old issue, so hopefully it is resolved by now.
For feature requests, feedback, and bug reports, please contact support@applitools.com
