### ISSUE TITLE
Cypress events not firing if eyes-cypress is enabled

### ISSUE THREAD

**Issue by paolo-chiabrera** [applitools/eyes.sdk.javascript1#693]
```
module.exports = (on) => {
  on('before:run', () => {
    console.log('before:run event')
  })

  on('after:run', () => {
    console.log('after:run event')
  })
}

require('@applitools/eyes-cypress')(module) // commenting this line will make the events fire again
```

Enabling `eyes-cypress` seems to not propagate all the events fired by Cypress and impossible to define custom hooks.

Ref [here](https://github.com/applitools/eyes.sdk.javascript1/blob/master/packages/eyes-cypress/src/plugin/pluginExport.js#L5)

**Comment by amitzur** [comment]
Hi @paolo-chiabrera ,

This is fixed in version `3.22.8`.
For feature requests, feedback, and bug reports, please contact support@applitools.com
