### ISSUE TITLE
Problems on Vite?

### ISSUE THREAD

**Issue by filiphric** [applitools/eyes.sdk.javascript1#698]
Hey there!

I’ve been trying to run `eyes-storybook` for a vue3/ts/vite project. It seems to me that this does not work at all, but maybe I’m doing something wrong. You can check out the problem on the [repo branch](https://github.com/filiphric/trelloapp-vue-vite-ts/tree/storybook) where I have been playing with storybook tests.

I try to run my tests with `npx eyes-storybook` script. It seems to start storybook, but it’s unable to read them. I get the error `Error: Eyes could not render stories properly.` for every story.

Happy to provide additional info if needed

**Comment by bsk26** [comment]
Are there still issues with `eyes-storybook` and storybook > 6.4? Upgrading to storybook 6.4.4 seems to have broken `eyes-storybook` for us

**Comment by amitzur** [comment]
Hi @filiphric and @bsk26 ,

Support for Storybook 6.4 was added in `@applitools/eyes-storybook` version `3.27.1`.
For feature requests, feedback, and bug reports, please contact support@applitools.com
