### ISSUE TITLE
[eyes-cypress] Inaccuracies in documentation

### ISSUE THREAD

**Issue by slikts** [applitools/eyes.sdk.javascript1#712]
The readme for eyes-cypress lists `baselineBranchName` as the option to set the branch name, but the actual option should be `branchName`, which is not mentioned, except as `APPLITOOLS_BRANCH_NAME`, which is inconsistent. `baselineBranchName` does not function properly: setting `baselineBranchName` does not show up in the Eyes UI. If `branchName` and `parentBranchName` are set, they are shown in the Eyes UI, but `baselineBranchName` allows to silently override this and actually check against a different branch.

`baselineBranchName` differs from `branchName` in that `baselineBranchName` does not create new branches, but it would be more clear to have, for example, a `saveNewBranches` option. `baselineBranchName` also does not have a clear error message: when `baselineBranchName` is set to a non-existent branch, the `eyesClose` API responds with 404 status code (which is the wrong status code, because it suggests that the API endpoint is missing) and a generic message: "Eyes-Cypress detected diffs or errors during execution of visual tests." Without details, this was difficult to debug, and to make it more confusing, even though the API responded with an error, the same tests in the Eyes UI show up as passing.

Other issues with the readme are that `compareWithParentBranch` and `saveNewTests` are *not* `false` by default. I've not reviewed the whole readme, so there might be more issues.

**Comment by amitzur** [comment]
Hi @slikts ,

This feedback is valid and valuable for us. We will do the necessary adjustments in the documentation and take your suggestions into account.

For feature requests, feedback, and bug reports, please contact support@applitools.com
