### ISSUE TITLE
[eyes-cypress] how to capture webgl canvas?

### ISSUE THREAD

**Issue by ronyf** [applitools/eyes.sdk.javascript1#719]
My program has [KeyLines](https://cambridge-intelligence.com/keylines/) graph which uses WebGL behind the scenes.

When I set KeyLines to work in canvas mode, it is captured well, but when it's WebGL the capture leaves a blank box where the graph should be.

Is there anything I should set to capture WebGL?

**Comment by kyryloonufriiev** [comment]
WebGL canvases are not capturable if you don't have a `preserveDrawingBuffer` property set to `true` during WebGL context creation. Since this is probably not something you are willing to do, because it might be a performance gap for the app, I can recommend you this workaround. Very important it should be executed **before** the navigation.

```js
before(() => {
  cy.log('preserving drawing buffer')
    .then(() => Cypress.automation('remote:debugger:protocol', {command: 'Page.enable'}))
    .then(() => Cypress.automation('remote:debugger:protocol', {
      command: 'Page.addScriptToEvaluateOnNewDocument',
      params: {
        source: `(function () {
          const getContext = HTMLCanvasElement.prototype.getContext
          if (getContext.isPatched) return
          HTMLCanvasElement.prototype.getContext = function(contextType, contextAttributes = {}) {
            if (['webgl', 'experimental-webgl', 'webgl2'].includes(contextType)) {
              contextAttributes.preserveDrawingBuffer = true
            }
            return getContext.call(this, contextType, contextAttributes)
          }
          HTMLCanvasElement.prototype.getContext.isPatched = true
        })()`
      },
    }))
})
```

**Comment by amitzur** [comment]
Hi @ronyf ,

For feature requests, feedback, and bug reports, please contact support@applitools.com
