### ISSUE TITLE
[eyes-storybook] Support interactive stories (play function)

### ISSUE THREAD

**Issue by penx** [applitools/eyes.sdk.javascript1#725]
Are interaction tests via the play function in Storybook 6.4 supported? If not, please can support be added?

https://storybook.js.org/blog/interactive-stories-beta/

**Comment by kyryloonufriiev** [comment]
This is not supported at the moment. I believe we would love to support it. Would you like to describe in some detail how do you imagining this is going to work?
I can definitely see that we are taking one screenshot before and one screenshot after playing. But maybe you have a better vision.

**Comment by penx** [comment]
I think to be useful for us right now, we'd only need a screenshot after playing. We can easily create multiple stories in order to capture screenshots midway.

Perhaps mid way screenshots could then be added as an enhancement at a later date, e.g. as:

```ts
import { takeScreenshot } from '@applitools/eyes-storybook'

MyStory.play = async ({ canvasElement }) => {
  const canvas = within(canvasElement);
  const themeButton = await canvas.findByRole('button', { name: 'Theme' });
  await fireEvent.click(themeButton);
  // TODO: await/assert something is visible at this step
  takeScreenshot();
  const menuItem = await canvas.findByRole('menuitem', { name: 'My Theme' });
  await fireEvent.click(menuItem);
  ```

**Comment by penx** [comment]
For now, would it be quick to update `'@applitools/eyes-storybook'` to make sure that, if a play function is present on a story, it waits until it is completed before taking the screenshot?

**Comment by amitzur** [comment]
Hi @penx ,

Thank you for this feedback! It is valuable for us and we're taking it into consideration.
For additional feature requests, feedback, and bug reports, please contact support@applitools.com
