### ISSUE TITLE
[eyes-storybook] Fails to start Storybook 6.4.x

### ISSUE THREAD

**Issue by bsk26** [applitools/eyes.sdk.javascript1#726]
`eyes-storybook` is broken for Storybook versions past 6.4. I reported this to the Applitools support but also making a bug here for public visibility.

The `eyes-storybook` command fails on a "storybook failed to start" timeout error, however, you can see that Storybook is actually starting in the background

Referenced in this issue: https://github.com/applitools/eyes.sdk.javascript1/issues/698

**Comment by amitzur** [comment]
Hi @bsk26 ,

Support for Storybook 6.4 was added in @applitools/eyes-storybook version 3.27.1.
For feature requests, feedback, and bug reports, please contact support@applitools.com
