### ISSUE TITLE
Typescript types?

### ISSUE THREAD

**Issue by dylang** [applitools/eyes.sdk.javascript1#73]
Hi, are typescript types planned to be included? 

I see some in `Eyes.Sdk.JavaScript` such as  [Eyes.Sdk.JavaScript/packages/eyes.sdk/typings/index.d.ts](https://github.com/applitools/Eyes.Sdk.JavaScript/blob/master/packages/eyes.sdk/typings/index.d.ts), but they don't seem to be in this repo.

I'm specifically looking for types for `@applitools/eyes-images`, which is covered by neither package.

**Comment by knorrium** [comment]
@astappiev @danielputerman @danielschwartz85 do you think this could be prioritized?

**Comment by danielputerman** [comment]
Hi @knorrium @dylang it's in our backlog of course, I will check what can be done about prioritization.

**Comment by danielschwartz85** [comment]
fyi - added Typescript definition file to visual-grid-client package:
https://github.com/applitools/eyes.sdk.javascript1/blob/master/packages/visual-grid-client/index.d.ts

**Comment by cipivanov** [comment]
Any updates on this?

**Comment by kyryloonufriiev** [comment]
TypeScript support is under active development and will be delivered with this PR https://github.com/applitools/eyes.sdk.javascript1/pull/305

**Comment by amitzur** [comment]
Hi all,

We indeed added support for TS types in the majority of our SDK's. But for `@applitools/eyes-images` this is not available yet.
For feature requests, feedback, and bug reports, please contact support@applitools.com
