### ISSUE TITLE
Where is @applitools/dom-snapshot in Github?

### ISSUE THREAD

**Issue by dylang** [applitools/eyes.sdk.javascript1#74]
This project depends on a project called `@applitools/dom-snapshot`. `@applitools/dom-snapshot` is published to [npm](https://www.npmjs.com/package/@applitools/dom-snapshot) and happens to include the source, but it would be helpful to have it on Github too to make it easier to submit tickets and PR's.

**Comment by danielschwartz85** [comment]
The repo is in giuthub at:
https://github.com/applitools/mono/tree/master/packages/dom-snapshot
Thanks.

**Comment by astappiev** [comment]
But the repo is Privat.

**Comment by tourdedave** [comment]
https://github.com/applitools/eyes.sdk.javascript1/tree/master/packages/dom-snapshot
