### ISSUE TITLE
@applitools/eyes-common/test/unit/utils/��onfigUtils.spec.js

### ISSUE THREAD

**Issue by dylang** [applitools/eyes.sdk.javascript1#75]
1. You are publishing tests. You should select what you want published by using the `files` array in `package.json`.

2. The file `СonfigUtils.spec.js` starts with a non-ascii character that just happens to look like a C.

For some reason this breaks Jenkins:
 
```
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /home/jenkins/workspace/78f00166/workspace/est_Eng_ci-org_argus_PR-166-DCVMOXVE46UCGXJAVR6C4QGP4AV6ZCRHPYDGBJGMUEOAMC66ZLGQ/node_modules/@applitools/eyes-common/test/unit/utils/��onfigUtils.spec.js
```

You can see in Github it's sorted last because it does not start with a C:

<img width="249" alt="Screen Shot 2019-05-07 at 3 53 27 PM" src="https://user-images.githubusercontent.com/51505/57328770-4f7ba800-70e0-11e9-8f7b-e7da374c13e5.png">

**Comment by astappiev** [comment]
Sorry. Fixed and published.
