### ISSUE TITLE
Security alert for axios version

### ISSUE THREAD

**Issue by JoMarton** [applitools/eyes.sdk.javascript1#78]
Hey, github notified me of a security issue with axios package (<= 0.18.0). I get it when installing `eyes-sdk-core` package through the `visual-grid-client`  

Please release a new version?
Thanks! 

links:
https://snyk.io/blog/a-denial-of-service-vulnerability-discovered-in-the-axios-javascript-package-affecting-all-versions-of-the-popular-http-client/

https://github.com/axios/axios/issues/2183

**Comment by astappiev** [comment]
Fixed in the new version.
