### ISSUE TITLE
close finally

### ISSUE THREAD

**Issue by saikrishna321** [applitools/eyes.sdk.javascript1#92]
@danielschwartz85 I'm using `@applitools/visual-grid-client` npm package. Is there a way to `close()` finally in the afterSuite rather than after each test. As its taking lot of time to verify on cloud. 

I tried to call the `close()` without `await` key thinking this would tell the grid client that test is closed, but when I check the applitools dashboard I don't see anything.

**Comment by danielschwartz85** [comment]
@saikrishna321 sorry for the late response, what Applitols SDK are you using ? what test framework are you using ?
This package is meant to be used an internal package for other Applitools specific test-framework SDKs.

_(but generally speaking the visual grid client is meant to be used by doing open + checkWindow + close many times, while saving the close promises and then doing `await Promis.all()` on them at the end of a test suit)_

**Comment by saikrishna321** [comment]
@danielputerman Thanks for getting back. Please have a look at the repo

https://github.com/saikrishna321/taiko-eyes

[Taiko.js](https://taiko.gauge.org/) is the open-source framework for browser automation which uses CDP.

Can you please take a look at the repo and help me understand if Applitools SDK was used in right way?

Thanks!

**Comment by danielschwartz85** [comment]
@saikrishna321 The framework & SDK Look very cool 💪 :-)

First Note that here:
https://github.com/saikrishna321/taiko-eyes/blob/master/src/eyes.js#L55
the `presult` function is used without getting the results. ( it returns an array with first index having an error if one is thrown and second index is the results if no error was thrown )
generally should be used like this:
 `const [errorIfExits, resultsIfNoError] = await presult(this._currentTest.eyes.close()); `

Regardless I would change: 
https://github.com/saikrishna321/taiko-eyes/blob/master/src/eyes.js#L55
to not wait but just save the close promise :
`this._closedTests.push( this._currentTest.eyes.close() );`

Then add a function `waitForResults` in `eyes` class to wait on all `closed` promises, something like:

```
async function waitForResults() {
      let results = await Promise.all(this._closedTests);
      if (results === undefined) {
        console.log('Eyes Test Passed!!');
      } else {
        const {failed, diffs} = await errorAndDiff(results);
        if (this._defaultConfig.failTaikoOnDiff) {
          if (failed.length || diffs.length) {
            const {failedStep, passedStep} = errorPerStep(results);
            throw new Error(errorDigest({failed, diffs, failedStep, passedStep}));
          }
        }
      }
}
```

_I have not tested this code and note that results might need to be iterated and each result checked by `errorAndDiff`.. not sure, have not checked it.._

LMK if this works / you have any other question 👍

**Comment by saikrishna321** [comment]
danielschwartz85  Thanks a lot for taking the time and looking at the code and giving feedback. I have made the changes as you suggested in this PR https://github.com/saikrishna321/taiko-eyes/pull/4/files

**Comment by saikrishna321** [comment]
Thanks @danielputerman 👍
